name: Terraform Code Sanity Check

on:
  push:
    branches:
      - master

jobs:
  Terraform-Saity-Check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.0.0

      # - name: Configure AWS Credentials
      #   uses: aws-actions/configure-aws-credentials@v1
      #   with:
      #     aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID_LOCAL }}
      #     aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_LOCAL }}
      #     aws-region: ${{ secrets.AWS_REGION }}

      - name: Terraform Format
        run: terraform fmt -recursive

      - name: Terraform Init
        run: |
          cd infra/dev
          terraform init

      - name: Terraform Validate
        run: |
          cd infra/dev
          terraform validate -no-color

      # - name: Terraform Plan
      #   run: |
      #     cd infra/dev
      #     terraform plan
